import os
import pickle
from shlex import split
import numpy as np
import pandas as pd
from google.cloud import bigquery
from google.oauth2 import service_account

# --- Configuration ---
CREDENTIALS_PATH = 'ml_engine/knitwear-app-37e6574c4829.json' # Path to your GCP service account JSON
master_features_file = 'features_DINO_yolo_pose_multicentroid.npy'
pattern_mapping_file = 'pattern_to_centroids_DINO_yolo_pose_multicentroid.pkl'

TARGET_TABLE = "knitwear-app.ravelry_data.dim_pattern_image_embeddings"

def upload_centroids_to_bigquery():
    # 1. Load the local files generated by your ML steps
    if not (os.path.exists(master_features_file) and os.path.exists(pattern_mapping_file)):
        raise FileNotFoundError("Missing local multi-centroid files. Run the feature extraction pipeline first.")
        
    all_centroids = np.load(master_features_file) # Sharp shape: (Total Centroids, 768)
    with open(pattern_mapping_file, 'rb') as f:
        pattern_to_centroid_indices = pickle.load(f) # Maps pattern_id -> [list of flat indices]

    print(f"Loaded {len(all_centroids)} total centroids across {len(pattern_to_centroid_indices)} unique patterns.")

    # 2. Reconstruct the flat vectors into a structured relational format
    rows_list = []
    for pattern_id, centroid_indices in pattern_to_centroid_indices.items():
        for order_idx, global_idx in enumerate(centroid_indices):
            vector = all_centroids[global_idx].tolist() # BigQuery requires a standard Python list, not a numpy array
            
            rows_list.append({
                "pattern_id": int("".join(filter(str.isdigit, str(pattern_id)))), # Assuming pattern_id format is 'pattern_12345'
                "centroid_index": int(order_idx), # Distinguishes centroid 0, 1, 2 for the same pattern
                "image_embedding": vector
            })

    df = pd.DataFrame(rows_list)
    print(f"Constructed DataFrame with {len(df)} structural rows ready for BigQuery upload.")

    # 3. Connect to BigQuery via your Service Account
    credentials = service_account.Credentials.from_service_account_file(CREDENTIALS_PATH)
    bq_client = bigquery.Client(credentials=credentials, project=credentials.project_id)

    # 4. Explicitly define the schema (Crucial for handling the FLOAT64 array column)
    job_config = bigquery.LoadJobConfig(
        schema=[
            bigquery.SchemaField("pattern_id", "INTEGER", mode="REQUIRED"),
            bigquery.SchemaField("centroid_index", "INTEGER", mode="REQUIRED"),
            # REPEATED FLOAT64 is how BigQuery maps structural dense vector layers
            bigquery.SchemaField("image_embedding", "FLOAT64", mode="REPEATED"),
        ],
        # Overwrite the table if you re-run this locally to avoid duplicating centroids
        write_disposition="WRITE_TRUNCATE", 
    )

    print(f"Streaming data to {TARGET_TABLE}...")
    load_job = bq_client.load_table_from_dataframe(df, TARGET_TABLE, job_config=job_config)
    load_job.result() # Blocks execution until the upload job successfully resolves
    
    print(f"✓ Successfully populated table '{TARGET_TABLE}' with your multi-centroid visual embeddings!")

if __name__ == "__main__":
    upload_centroids_to_bigquery()